### ISSUE TITLE
Clickable inside tag cloud child sometimes doesn't work

### ISSUE THREAD

**Issue by mdrlzy** [oleksandrbalan/tagcloud#1]
Click can be interpreted as a drag, if at the moment of the click you move your finger even by a pixel, the `clickable` modifier will not be called
(Successful click should change screen)

https://github.com/oleksandrbalan/tagcloud/assets/85668474/05d963ee-350d-4709-89cb-298027d69350

**Comment by oleksandrbalan** [comment]
Fixed in [1.0.1](https://github.com/oleksandrbalan/tagcloud/releases/tag/v1.0.1) 👍
